version: "3.9"

volumes:
  database: # Define o volume que será usado pelo serviço `db`
    driver: local

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - 5173:5173
    networks:
      - easyfinance_network
    environment:
      - VITE_PORT=5173
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 3000:3000
    networks:
      - easyfinance_network
  db: 
    image: bitnami/postgresql:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=easyfinance_db
    volumes:
      - database:/var/lib/postgres
    networks:
      - easyfinance_network

networks:
  easyfinance_network:
    external: true
