@baseUrl = http://localhost:3030
@authToken = {{authenticate.response.body.token}}

###

# @name create-account
POST {{baseUrl}}/accounts 
Content-Type: application/json

{
    "name": "Tiago Emanuel",
    "email": "tiagoepitanga10@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
    "email": "tiagoepitanga10@gmail.com",
    "password": "123456"
}


###

# @name recover-password
POST {{baseUrl}}/auth/request-recover-password
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "email": "tiagoepitanga10@gmail.com"
}

###

# @name create-task
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Fazer almoço"
}

###

# @name get-tasks
GET {{baseUrl}}/tasks?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name get-profile
GET {{baseUrl}}/sessions/get-profile
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name delete-task
DELETE  {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "id": "99db9fac-166a-4e90-ad26-05f4aa8790e8"
}

###

# @name get-task-by-id
GET  {{baseUrl}}/tasks/63f76395-8dd2-41db-b1c3-debe22d7c90d
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name put-task
PUT  {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "id": "63f76395-8dd2-41db-b1c3-debe22d7c90d",
    "name": "Fazer janta"
}

